"""Native ISO/TS 18571 DTW helpers."""

from typing import Callable

from ._core import (
    DtwLayout,
    ParallelMode,
    ReductionMode,
    SimdLevel,
    SimdTargetMode,
    _magnitude_ratio_variant_avx2_all,
    _magnitude_ratio_variant_avx2_dtw_local_cost,
    _magnitude_ratio_variant_avx2_fma_all,
    _magnitude_ratio_variant_avx2_fma_dtw_local_cost,
    _magnitude_ratio_variant_avx2_fma_gradient_only,
    _magnitude_ratio_variant_avx2_fma_magnitude_path,
    _magnitude_ratio_variant_avx2_fma_phase_products,
    _magnitude_ratio_variant_avx2_fma_slope_smoothing,
    _magnitude_ratio_variant_avx2_gradient_only,
    _magnitude_ratio_variant_avx2_magnitude_path,
    _magnitude_ratio_variant_avx2_phase_products,
    _magnitude_ratio_variant_avx2_slope_smoothing,
    _magnitude_ratio_variant_scalar_all,
    _magnitude_ratio_variant_scalar_dtw_local_cost,
    _magnitude_ratio_variant_scalar_gradient_only,
    _magnitude_ratio_variant_scalar_magnitude_path,
    _magnitude_ratio_variant_scalar_phase_products,
    _magnitude_ratio_variant_scalar_slope_smoothing,
    _magnitude_ratio_variant_sse2_all,
    _magnitude_ratio_variant_sse2_dtw_local_cost,
    _magnitude_ratio_variant_sse2_gradient_only,
    _magnitude_ratio_variant_sse2_magnitude_path,
    _magnitude_ratio_variant_sse2_phase_products,
    _magnitude_ratio_variant_sse2_slope_smoothing,
    _parallel_barrier_overhead,
    _resolve_simd_level,
    _score_components_variant_avx2_all,
    _score_components_variant_avx2_dtw_local_cost,
    _score_components_variant_avx2_fma_all,
    _score_components_variant_avx2_fma_dtw_local_cost,
    _score_components_variant_avx2_fma_gradient_only,
    _score_components_variant_avx2_fma_magnitude_path,
    _score_components_variant_avx2_fma_phase_products,
    _score_components_variant_avx2_fma_slope_smoothing,
    _score_components_variant_avx2_gradient_only,
    _score_components_variant_avx2_magnitude_path,
    _score_components_variant_avx2_phase_products,
    _score_components_variant_avx2_slope_smoothing,
    _score_components_variant_scalar_all,
    _score_components_variant_scalar_dtw_local_cost,
    _score_components_variant_scalar_gradient_only,
    _score_components_variant_scalar_magnitude_path,
    _score_components_variant_scalar_phase_products,
    _score_components_variant_scalar_slope_smoothing,
    _score_components_variant_sse2_all,
    _score_components_variant_sse2_dtw_local_cost,
    _score_components_variant_sse2_gradient_only,
    _score_components_variant_sse2_magnitude_path,
    _score_components_variant_sse2_phase_products,
    _score_components_variant_sse2_slope_smoothing,
    _simd_info,
    backend_info,
    magnitude_ratio,
    score_components,
    warp_path,
)

_SCORE_VARIANTS: dict[tuple[SimdLevel, SimdTargetMode], Callable[..., dict]] = {
    (SimdLevel.Scalar, SimdTargetMode.GradientOnly): _score_components_variant_scalar_gradient_only,
    (SimdLevel.Scalar, SimdTargetMode.PhaseProducts): _score_components_variant_scalar_phase_products,
    (SimdLevel.Scalar, SimdTargetMode.DtwLocalCost): _score_components_variant_scalar_dtw_local_cost,
    (SimdLevel.Scalar, SimdTargetMode.SlopeSmoothing): _score_components_variant_scalar_slope_smoothing,
    (SimdLevel.Scalar, SimdTargetMode.MagnitudePath): _score_components_variant_scalar_magnitude_path,
    (SimdLevel.Scalar, SimdTargetMode.All): _score_components_variant_scalar_all,
    (SimdLevel.Sse2, SimdTargetMode.GradientOnly): _score_components_variant_sse2_gradient_only,
    (SimdLevel.Sse2, SimdTargetMode.PhaseProducts): _score_components_variant_sse2_phase_products,
    (SimdLevel.Sse2, SimdTargetMode.DtwLocalCost): _score_components_variant_sse2_dtw_local_cost,
    (SimdLevel.Sse2, SimdTargetMode.SlopeSmoothing): _score_components_variant_sse2_slope_smoothing,
    (SimdLevel.Sse2, SimdTargetMode.MagnitudePath): _score_components_variant_sse2_magnitude_path,
    (SimdLevel.Sse2, SimdTargetMode.All): _score_components_variant_sse2_all,
    (SimdLevel.Avx2, SimdTargetMode.GradientOnly): _score_components_variant_avx2_gradient_only,
    (SimdLevel.Avx2, SimdTargetMode.PhaseProducts): _score_components_variant_avx2_phase_products,
    (SimdLevel.Avx2, SimdTargetMode.DtwLocalCost): _score_components_variant_avx2_dtw_local_cost,
    (SimdLevel.Avx2, SimdTargetMode.SlopeSmoothing): _score_components_variant_avx2_slope_smoothing,
    (SimdLevel.Avx2, SimdTargetMode.MagnitudePath): _score_components_variant_avx2_magnitude_path,
    (SimdLevel.Avx2, SimdTargetMode.All): _score_components_variant_avx2_all,
    (SimdLevel.Avx2Fma, SimdTargetMode.GradientOnly): _score_components_variant_avx2_fma_gradient_only,
    (SimdLevel.Avx2Fma, SimdTargetMode.PhaseProducts): _score_components_variant_avx2_fma_phase_products,
    (SimdLevel.Avx2Fma, SimdTargetMode.DtwLocalCost): _score_components_variant_avx2_fma_dtw_local_cost,
    (SimdLevel.Avx2Fma, SimdTargetMode.SlopeSmoothing): _score_components_variant_avx2_fma_slope_smoothing,
    (SimdLevel.Avx2Fma, SimdTargetMode.MagnitudePath): _score_components_variant_avx2_fma_magnitude_path,
    (SimdLevel.Avx2Fma, SimdTargetMode.All): _score_components_variant_avx2_fma_all,
}

_MAGNITUDE_VARIANTS: dict[tuple[SimdLevel, SimdTargetMode], Callable[..., float]] = {
    (SimdLevel.Scalar, SimdTargetMode.GradientOnly): _magnitude_ratio_variant_scalar_gradient_only,
    (SimdLevel.Scalar, SimdTargetMode.PhaseProducts): _magnitude_ratio_variant_scalar_phase_products,
    (SimdLevel.Scalar, SimdTargetMode.DtwLocalCost): _magnitude_ratio_variant_scalar_dtw_local_cost,
    (SimdLevel.Scalar, SimdTargetMode.SlopeSmoothing): _magnitude_ratio_variant_scalar_slope_smoothing,
    (SimdLevel.Scalar, SimdTargetMode.MagnitudePath): _magnitude_ratio_variant_scalar_magnitude_path,
    (SimdLevel.Scalar, SimdTargetMode.All): _magnitude_ratio_variant_scalar_all,
    (SimdLevel.Sse2, SimdTargetMode.GradientOnly): _magnitude_ratio_variant_sse2_gradient_only,
    (SimdLevel.Sse2, SimdTargetMode.PhaseProducts): _magnitude_ratio_variant_sse2_phase_products,
    (SimdLevel.Sse2, SimdTargetMode.DtwLocalCost): _magnitude_ratio_variant_sse2_dtw_local_cost,
    (SimdLevel.Sse2, SimdTargetMode.SlopeSmoothing): _magnitude_ratio_variant_sse2_slope_smoothing,
    (SimdLevel.Sse2, SimdTargetMode.MagnitudePath): _magnitude_ratio_variant_sse2_magnitude_path,
    (SimdLevel.Sse2, SimdTargetMode.All): _magnitude_ratio_variant_sse2_all,
    (SimdLevel.Avx2, SimdTargetMode.GradientOnly): _magnitude_ratio_variant_avx2_gradient_only,
    (SimdLevel.Avx2, SimdTargetMode.PhaseProducts): _magnitude_ratio_variant_avx2_phase_products,
    (SimdLevel.Avx2, SimdTargetMode.DtwLocalCost): _magnitude_ratio_variant_avx2_dtw_local_cost,
    (SimdLevel.Avx2, SimdTargetMode.SlopeSmoothing): _magnitude_ratio_variant_avx2_slope_smoothing,
    (SimdLevel.Avx2, SimdTargetMode.MagnitudePath): _magnitude_ratio_variant_avx2_magnitude_path,
    (SimdLevel.Avx2, SimdTargetMode.All): _magnitude_ratio_variant_avx2_all,
    (SimdLevel.Avx2Fma, SimdTargetMode.GradientOnly): _magnitude_ratio_variant_avx2_fma_gradient_only,
    (SimdLevel.Avx2Fma, SimdTargetMode.PhaseProducts): _magnitude_ratio_variant_avx2_fma_phase_products,
    (SimdLevel.Avx2Fma, SimdTargetMode.DtwLocalCost): _magnitude_ratio_variant_avx2_fma_dtw_local_cost,
    (SimdLevel.Avx2Fma, SimdTargetMode.SlopeSmoothing): _magnitude_ratio_variant_avx2_fma_slope_smoothing,
    (SimdLevel.Avx2Fma, SimdTargetMode.MagnitudePath): _magnitude_ratio_variant_avx2_fma_magnitude_path,
    (SimdLevel.Avx2Fma, SimdTargetMode.All): _magnitude_ratio_variant_avx2_fma_all,
}


def score_variant_function(simd_level: SimdLevel, simd_target_mode: SimdTargetMode) -> Callable[..., dict]:
    return _SCORE_VARIANTS[(simd_level, simd_target_mode)]


def magnitude_variant_function(simd_level: SimdLevel, simd_target_mode: SimdTargetMode) -> Callable[..., float]:
    return _MAGNITUDE_VARIANTS[(simd_level, simd_target_mode)]


__all__ = [
    "DtwLayout",
    "ParallelMode",
    "ReductionMode",
    "SimdLevel",
    "SimdTargetMode",
    "_parallel_barrier_overhead",
    "_resolve_simd_level",
    "_simd_info",
    "backend_info",
    "magnitude_variant_function",
    "magnitude_ratio",
    "score_variant_function",
    "score_components",
    "warp_path",
]
